name: Run POSTMAN collection 
on: 
  push:
    branches:
      - master
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm i npm@latest
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: make Directory for results
        run: mkdir -p testResults
      - name: Run Postman collection
        run: |
          newman run ./store.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RurReports
          path: testResults


